name: 'Setup Btormc'
description: 'Tool for install Btormc env'
branding:
  icon: 'message-circle'
  color: 'red'
# inputs:
#   action:  # action
#     description: 'automate tedious tasks'
#     required: true
runs:
  using: "node16"
  main: "dist/index.js"
